<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RollForward>Major</RollForward>
    <IsPackable>false</IsPackable>
    <ShouldBeValidatedAsExecutableReference>false</ShouldBeValidatedAsExecutableReference>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Markazor.Build.Tests" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Markazor\Markazor.csproj" />
  </ItemGroup>
</Project>
